@startuml
title Aircraft
class Aircraft
{
    - _passengerCapacity:int
    - _fuelCapacity:int
    - _currentFuel:int
    + TailNumber:string
    + Model: string
    + PassengerCapacity:int
    + FuelCapacity:int
    + CurrentFuel:int
    + Aircraft(tailNumber:string, model:string)
    + Aircraft(tailNumber:string, model:string,currentFuel:int,passengerCapacity:int)
    + SetFuel(fuelAmount:int)
    + AddFuel(fuel:int)
}
@enduml