@startuml
title Flight
class Flight
{
    - _passengerCount:int
    + FlightNumber:string?
    + Destination:string?
    + ArrivalTime:DateTime
    + DepartureTime:DateTime
    + PassengerCount:int
    + Aircraft:Aircraft?
    + Gate:Gate?
    + CanCarryPassenger()

}
@enduml